In [3]:
input("Please enter user input:\n")

Please enter user input:
checking


'checking'

In [6]:
import numpy as np
a= np.array([[1,2],[3,4]],dtype=np.float64)

In [7]:
b= np.array([[5,6],[7,8]],dtype=np.float64)

In [8]:
a

array([[1., 2.],
       [3., 4.]])

In [9]:
b

array([[5., 6.],
       [7., 8.]])

In [10]:
print(a+b)

[[ 6.  8.]
 [10. 12.]]


In [11]:
print(np.add(a,b))

[[ 6.  8.]
 [10. 12.]]


In [12]:
print(np.subtract(a,b))

[[-4. -4.]
 [-4. -4.]]


In [13]:
print(np.multiply(a,b))

[[ 5. 12.]
 [21. 32.]]


In [14]:
print(np.divide(a,b))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [16]:
print(np.sqrt(a))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [17]:
c = np.array([9,10],dtype=np.float64)

In [18]:
print(np.add(a,c))

[[10. 12.]
 [12. 14.]]


In [20]:
print(c+a)

[[10. 12.]
 [12. 14.]]


In [21]:
print(np.multiply(a,c))

[[ 9. 20.]
 [27. 40.]]


In [22]:
print(np.dot(a,c))

[29. 67.]


In [23]:
a

array([[1., 2.],
       [3., 4.]])

In [24]:
print(np.sum(a,axis=0))

[4. 6.]


In [25]:
print(np.sum(a,axis=1))

[3. 7.]


In [26]:
z = np.sum(a,axis=1)

In [28]:
z.shape

(2,)

In [29]:
#TUPLE
#immutable
#list is mutable....
t = 90,95,45,30

In [31]:
print(type(t))

<class 'tuple'>


In [32]:
print(t)

(90, 95, 45, 30)


In [33]:
t = (123,345,56,78,9)

In [34]:
print(t)

(123, 345, 56, 78, 9)


In [35]:
print(t[0])

123


In [36]:
print(t[1:4])

(345, 56, 78)


In [37]:
t[1]=456

TypeError: 'tuple' object does not support item assignment

In [38]:
t.append(45)

AttributeError: 'tuple' object has no attribute 'append'

In [39]:
print(max(t))

345


In [40]:
print(min(t))

9


In [41]:
del t[1]

TypeError: 'tuple' object doesn't support item deletion

In [42]:
del t

In [43]:
t

NameError: name 't' is not defined

In [44]:
t = (123,456,789,45,324,45,56)

In [45]:
print(sum(t))

1838


In [ ]:
#Dictionary