In [3]:
input("Please enter user input:\n")

Please enter user input:
checking


'checking'

In [6]:
import numpy as np
a= np.array([[1,2],[3,4]],dtype=np.float64)

In [7]:
b= np.array([[5,6],[7,8]],dtype=np.float64)

In [8]:
a

array([[1., 2.],
       [3., 4.]])

In [9]:
b

array([[5., 6.],
       [7., 8.]])

In [10]:
print(a+b)

[[ 6.  8.]
 [10. 12.]]


In [11]:
print(np.add(a,b))

[[ 6.  8.]
 [10. 12.]]


In [12]:
print(np.subtract(a,b))

[[-4. -4.]
 [-4. -4.]]


In [13]:
print(np.multiply(a,b))

[[ 5. 12.]
 [21. 32.]]


In [14]:
print(np.divide(a,b))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [16]:
print(np.sqrt(a))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [17]:
c = np.array([9,10],dtype=np.float64)

In [18]:
print(np.add(a,c))

[[10. 12.]
 [12. 14.]]


In [20]:
print(c+a)

[[10. 12.]
 [12. 14.]]


In [21]:
print(np.multiply(a,c))

[[ 9. 20.]
 [27. 40.]]


In [22]:
print(np.dot(a,c))

[29. 67.]


In [23]:
a

array([[1., 2.],
       [3., 4.]])

In [24]:
print(np.sum(a,axis=0))

[4. 6.]


In [25]:
print(np.sum(a,axis=1))

[3. 7.]


In [26]:
z = np.sum(a,axis=1)

In [28]:
z.shape

(2,)